export const szinekLista=["red","blue","green","yellow","orange","purple"]
export const generaltLista=["white","white","white","white"]
export const visszajelzesListaM=[
    ["gray","gray","gray","gray"]
    ["gray","gray","gray","gray"]
    ["gray","gray","gray","gray"]
    ["gray","gray","gray","gray"]
    ["gray","gray","gray","gray"]
    ["gray","gray","gray","gray"]
    ["gray","gray","gray","gray"]
    ["gray","gray","gray","gray"]
    ["gray","gray","gray","gray"]
    ["gray","gray","gray","gray"]
]

export const tippListaM=[
    ["white","white","white","white"]
    ["white","white","white","white"]
    ["white","white","white","white"]
    ["white","white","white","white"]
    ["white","white","white","white"]
    ["white","white","white","white"]
    ["white","white","white","white"]
    ["white","white","white","white"]
    ["white","white","white","white"]
    ["white","white","white","white"]
]

